branches:
  only:
    - master
language: node_js
node_js:
  - 14
#cache:
#  directories:
#   - node_modules
install:
  - pnpm install
script:
  - pnpm build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master